exec-once = swww-daemon
exec-once = waybar
exec-once = nm-applet
exec-once = swaync -c ~/.config/swaync/config.json -s ~/.config/swaync/style.css
exec-once = hypridle
exec-once = /usr/libexec/polkit-mate-authentication-agent-1
exec-once = /usr/libexec/kdeconnectd
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Ice'
exec-once = pyprland

exec-once = [workspace special:scratch silent] kitty
exec-once = [workspace 2 silent] spotify
exec-once = [workspace 2 silent] kitty --title terminal_cava  -e cava
exec-once = [workspace 2 silent] kitty --title terminal_stats -e bash -c "fastfetch; read"
