plugin {
    hyprbars {
        bar_height = 28
        bar_color = rgba(1e1e2ee6)
        col.text = rgb(cdd6f4)
        bar_text_size = 10
        bar_text_font = JetBrainsMono Nerd Font
        bar_part_of_window = true
        bar_precedence_over_border = true

        hyprbars-button = rgb(f38ba8), 12, 󰅖, hyprctl dispatch killactive
        hyprbars-button = rgb(a6e3a1), 12, 󰍹, hyprctl dispatch togglefloating
    }
}
