windowrulev2 = workspace 2, title:^(terminal_cava)$
windowrulev2 = workspace 2, title:^(terminal_stats)$
windowrulev2 = workspace 2, class:^(Spotify)$

windowrulev2 = workspace 3, class:^(code-url-handler)$
windowrulev2 = workspace 3, class:^(code)$

windowrulev2 = opacity 0.90 0.80, class:^(code-url-handler)$
windowrulev2 = opacity 0.90 0.80, class:^(code)$
windowrulev2 = opacity 0.85 0.75, class:^(steam)$
windowrulev2 = opacity 0.85 0.75, class:^(nemo)$

windowrulev2 = immediate, class:^(steam_app_1422450)$

windowrulev2 = float,         workspace:special:scratch
windowrulev2 = size 1200 700, workspace:special:scratch
windowrulev2 = center,        workspace:special:scratch

windowrulev2 = float,  class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = size 800 600, class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = center, class:^(org.pulseaudio.pavucontrol)$

windowrulev2 = float,  class:^(blueman-manager)$
windowrulev2 = size 800 600, class:^(blueman-manager)$
windowrulev2 = center, class:^(blueman-manager)$

windowrulev2 = float,  class:^(nm-connection-editor)$
windowrulev2 = size 700 500, class:^(nm-connection-editor)$
windowrulev2 = center, class:^(nm-connection-editor)$

windowrulev2 = float,  class:^(nwg-look)$
windowrulev2 = size 900 650, class:^(nwg-look)$
windowrulev2 = center, class:^(nwg-look)$

windowrulev2 = float, class:^(nemo)$
windowrulev2 = size 1000 650, class:^(nemo)$
windowrulev2 = center, class:^(nemo)$
windowrulev2 = opacity 0.90 0.82, class:^(nemo)$

windowrule = suppressevent maximize, class:.*
windowrule = nofocus, class:^$, title:^$, xwayland:1, floating:1, fullscreen:0, pinned:0

windowrulev2 = float, class:^(waypaper)$
windowrulev2 = size 840 450, class:^(waypaper)$
windowrulev2 = center, class:^(waypaper)$
windowrulev2 = opacity 0.82 0.75, class:^(waypaper)$

layerrule = blur,        swaync-control-center
layerrule = blur,        swaync-notification-window
layerrule = blur,        waypaper
layerrule = ignorezero,  swaync-control-center
layerrule = ignorezero,  swaync-notification-window
layerrule = ignorealpha 0.5, swaync-control-center
layerrule = ignorealpha 0.5, swaync-notification-window
layerrule = animation slide right, swaync-control-center
layerrule = animation popin 85%,   swaync-notification-window

layerrule = blur,       rofi
layerrule = ignorezero, rofi

layerrule = blur,       nwg-drawer
layerrule = ignorezero, nwg-drawer
layerrule = blur,       nwg-panel
layerrule = ignorezero, nwg-panel
layerrule = blur,       nwg-control-center
layerrule = animation slide bottom, nwg-drawer

layerrule = blur,       wlogout
layerrule = ignorezero, wlogout
